import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox','--use-gl=swiftshader'] });
const p = await b.newPage({ viewport:{width:900,height:520} });
await p.addInitScript(()=>{ localStorage.setItem('lea_fiona_v2', JSON.stringify({version:2,profiles:[{id:'p_t',name:'Fiona',unlockedLevels:13,bestScores:[],bestTimes:[],totalCoins:0,stickers:[],settings:{unlockAllWorlds:true,assistInvincible:true,musicVolume:0,sfxVolume:0,quality:'high',screenShake:true}}],activeProfileId:'p_t'})); });
await p.goto('file:///tmp/real.html'); await p.waitForTimeout(1100);
const c = await p.$('[aria-label="Figur Fiona"]'); if (c) await c.click();
await p.waitForTimeout(220);
const lvl = await p.$(`[aria-label^="Level 10:"]`); if (lvl) await lvl.click();
await p.waitForTimeout(1500);
const cx=3520;
await p.evaluate((cx)=>{const g=window.__game;g.hitStopFrames=999999;g.camera.x=cx;g.camera.targetX=cx;},cx);
await p.waitForTimeout(140);
const info = await p.evaluate(()=>{const g=window.__game;const cp=g.checkpointDrawPos;const s=g.camera.worldToScreenInto(cp.x,cp.y,{x:0,y:0});const s2=g.camera.worldToScreenInto(cp.x,cp.y+cp.poleHeight,{x:0,y:0});return {cp, camx:g.camera.x, camy:g.camera.y, zoom:g.camera.zoom, dz:g.dynamicZoom, iz:g.impactZoom, topScreen:s, botScreen:s2, TILE:32};});
console.log(JSON.stringify(info,null,1));
await b.close();
