import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox','--use-gl=swiftshader'] });
const p = await b.newPage({ viewport:{width:900,height:520} });
await p.addInitScript(()=>{ localStorage.setItem('lea_fiona_v2', JSON.stringify({version:2,profiles:[{id:'p_t',name:'Fiona',unlockedLevels:13,bestScores:[],bestTimes:[],totalCoins:0,stickers:[],settings:{unlockAllWorlds:true,assistInvincible:true,musicVolume:0,sfxVolume:0,quality:'high',screenShake:true}}],activeProfileId:'p_t'})); window.__BANDDBG=true; });
await p.goto('file:///tmp/real.html'); await p.waitForTimeout(1000);
const c = await p.$('[aria-label="Figur Fiona"]'); if (c) await c.click(); await p.waitForTimeout(200);
const lvl = await p.$(`[aria-label^="Level 5:"]`); if (lvl) await lvl.click(); await p.waitForTimeout(1400);
await p.evaluate(()=>{window.__BANDLOGGED=false; const g=window.__game;g.hitStopFrames=999999;const cx=66*32-430;g.camera.x=cx;g.camera.targetX=cx;});
await p.waitForTimeout(200);
const segs = await p.evaluate(()=>window.__SEGS);
console.log('segments:', segs);
await b.close();
